### ISSUE TITLE
Create simple Hono demo

### ISSUE THREAD

**Issue by wisack** [smaddis/common-issues#12]
Create simple Hono demo. 

Demo should display
1. Deployment of Hono to K8S. Optionally also creation of K8S cluster.
2. Creation of tenants and devices to Hono
3. Examples of device that sends messages to Hono and a client that listens to these messages-

`1.` will probably be done using Terraform + helm

`2.` and `3.` are kind of ready in https://github.com/smaddis/hono-tests-private , but the repo is still cluttered. @hjhsalo should be involved in this work

See linked issues:
Linked #9
Linked #5
Linked #7

**Comment by wisack** [comment]
First part of this issue is resolved in smad-hono/deploy-WIP fork. It builds a cluster, deploys Hono images and allows to continue development in command line. 

Documentation to create tenant, add device, add credentials, start receiver, publish telemetry available in Google drive under documents folder. Tested and it works. Also Jaeger shows signs of life. 
I tried using ctron/hot but couldn't get it to work and I can't see what are the benefits compared to just using hono cli and curl

**Comment by hjhsalo** [comment]
Thanks for taking the time to handle this. I checked the instructions in Google Drive and they look fine. Was there a reason to choose Google Drive over markdown in a git repo, e.g. smad-hono?

> Also Jaeger shows signs of life.

Great

I would not close this until smad-hono/deploy-WIP is merged to smad-hono/master and documentation is stored alongside code.
Commit history on smad-hono/deploy-WIP needs squashing, but otherwise it seemed fine.
Is it OK if I reopen this and we close it after the changes above have been implemented?

> I can't see what are the benefits compared to just using hono cli and curl
User-friendliness is a benefit in my opinion. ctron/hat looks like a nice cli tool for administrating Hono. ctron/hot provides more uniform way of listening and sending messages to/from Hono than hono-cli .jar-package and curl. 

I haven't tested either hat or hot, so I cannot say much whether they work or not.
Do you want to take another look next week together?

**Comment by wisack** [comment]
Sure let's open it again.  I pushed documentation to deploy-WIP branch just now. I can try to use hot and hat tomorrow and am available to check how they work next week together as well.

**Comment by msrn** [comment]
With https://github.com/smaddis/smad-deploy-azure/pull/48 I think we have all parts done for a demo. I'm in favour of closing this issue.
